// <auto-generated />
using HelloWorldMvcApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace HelloWorldMvcApp.Migrations
{
    [DbContext(typeof(HelloWorldContext))]
    [Migration("20180523010155_AddingGradesTable")]
    partial class AddingGradesTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HelloWorldMvcApp.Models.Grades", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("StudentAssignment");

                    b.Property<int>("StudentID");

                    b.Property<string>("StudentName")
                        .IsRequired();

                    b.Property<int>("SubjectName");

                    b.Property<string>("TeacherName")
                        .IsRequired();

                    b.Property<string>("TeacherNotes")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Grades");
                });

            modelBuilder.Entity("HelloWorldMvcApp.Models.Student", b =>
                {
                    b.Property<int>("StudentID")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("MyBooleanValue");

                    b.Property<string>("StudentAddress");

                    b.Property<int>("StudentAge");

                    b.Property<int>("StudentEnrolled");

                    b.Property<int>("StudentGender");

                    b.Property<int>("StudentGradeLevel");

                    b.Property<string>("StudentName")
                        .IsRequired();

                    b.HasKey("StudentID");

                    b.ToTable("Student");
                });
#pragma warning restore 612, 618
        }
    }
}
